sudo: required

language: java

services:
- docker

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

before_install:
- chmod +x gradlew

install:
- "./gradlew build -Dscan"

before_script:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
- export DOCKER_REPO=takispravy/hello-bot
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH | tr '/' '-' ; fi`
- docker build -t $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER .
- docker tag $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER $DOCKER_REPO:$TAG
- docker push $DOCKER_REPO

env:
  global:
  - secure: indfWbycYLcyqh3UkqR/0GmFQdUUmhY8YL2IoAbT6D9enVT0A8ny7hn3mjACHmXfsdeYUIxo5jOvZ7kpm8wUHS3unG9RCS5CgF3L913xJI3QTkAGlREHGq6vLZhOKG2ekdhsnSU9wwGs9IsJ7KSCNG+LFIcOcZ3Vb4GHQPVCFhrLGhm6C7Lrc3UDX/M0O+W1FTFWnSVFGLNNpbpjnAD/q0xS7G4068zxPrJ4B7T5axmXj8TElMmsX3R+5HZk1p0lrXlezfdEeWouMmhq9wsw9t3xkL3Eu2ub2ePl5nI93nmEAcBW0PMmo3XWQqUatRFqjyGwrIpnZZESI0RbCOkJ4pNnMtSTw+zadcQM7VcLROjuqz0cLwwz5jaQnXUKKeX27TE20kYXnZWuBkBzqM3zA9ohLyeaCfZ8/gELyxOq8n3xwyH5tTGQObhpFEBFCWODygD0hiAA9xU3/gBLROHnxpeBzbOdHbqK7tlrsYNo9d0NH0SJR+UBymNWd1zaDVhYTCmxNVjXvUteZgR/wiXDBQS2KMBipcFNz6pHBvxbbWvDF5bBm/m6jLjkSvCwR9/gjwkb75+0313WmQBVpaZn7i/vhsAImOvPGW0ymFbx8LL4yPVf023fKvWwonvdNJHyLU+/EbvymKW+E0jTOnoc7fcUYCSkDlQj6MPsze/ds8o=
  - secure: Ai6bVTvBhQOcez+pweQH1QJc4Pc7u29vVAH4oVybU0zIlkuRh3TF/PDrjP7pu6+wnYS8Jy01mSzXGFtWOcH6BuTHx1S/gA4NYFE+Oe0WmlSZtJ1kpCe1VX9O6Hqrmr73Q5armXWz36i7w/m8oUTaAkcFsT6LhTtRrlAGY+l2jyU66awYjpOgVNuQVkq6IMewif2yeuRndr656jetsaTIGoSwxN4UDJfch66EGUELpEmvkX1S7jdYM4AYGsZf7YlBaoEbXcMjom78RDRK3NmamNCyguxI60H7rJqlaEgfhcooQG++vCVSXEDHTceXGr8DWaxl3mnDqEnUNPyzPam93yai74+MsCnsNLY2FPRT8rEfF/1aDjdLQBJbmAj/St7YojPRSUSgJFgDy2pShlFhZtI6a5AJEx5Eqm8jOmPwpzn3wfiyx59wbzVcglwSXxAoBI9jsta+1+/9YNhXln9tJDS4qCnjk5xa5a78EQUFHpFzYA+iLd5g5SbG+DYdtOnS9nPS2EZuFI23HEcGD2KU4cQM5ps5rhh906StOevlE1irI5U1nbFMV9JxiChKvxp4agkJJ5vN7KDQNIHzsQGbpzHI4lKxuHEioC4xhtQxTP3xz+N1YvX3OKvZovfCxODgdGIOer7vc18Tgiow2746AGNYQlS9t0QGjXsBjcvE0vA=
  - secure: cZGlTIz0/tHSmHgm8ip6qiLdCB+w6ZBxncZPOfu2Ik8vBB4fDrc60B6dwK1fttjW/+k0q6NE9gQ77m03qmmNOJ6Kb22H/P/YsFS1DUH3B6GZO6vUuCKY2mUbnPYJFy2Y7OHwi7bwG9MreRjcpDM49akyw1XxjJSrp+6R5Qkc7s9W/YW0gT4mGCbavDospx8ombqcCPJoJev7Rz4/on/LGJuTpR6YcTqjHS3ifqHpt8a4migi8NAqDxmxuK1sIti9554kWSNzzFizexEqnvBJTTuJMuY2LhOXrXLeSyKp2wfNHu5CnaKdu0M5zjRYXJJPHc8EFqBEYrV3LsJuWmxuDPPy5VJ4/GlGlL5tqH6Ov1qvCx8c3vfzdSMH5xcEvIhWKvmr5Yn5+lWfTaM9C5Hfs7ZycTVxX8ih4u1TvQsOgmbnl8Fqv/AiZ6dP22W18aljl5aGGN2NZo9nbsmig7uIyo9s4SM3vG9ac2BT8C9ZouVUueCIiY3tNmHKCu50dhRNIfgDpiwyuLnkkxYQlPpYifa4Gxy8h3p7JCMJqmzlCwNpB4Wim2Yn5iTNyR1qtmuR9eqcW0IBgJ8FoPMvSAqtOkj3PYQJM1buA93Pgu68qinDQj29qlKN9DxZai4T8gjO4b1q5XGMbX8CiX2oemIFz+nUtGArv3ryW47cCFrjSBQ=
